# File : .pep8speaks.yml

message:
    opened:
        header: "Hello @{name}, thank you for submitting this PR!"
        footer: "In need of guides? [Guidelines for PEP-8](https://pep8.org/) and [Hitchhiker's guide to code style](https://python-guide.readthedocs.io/en/latest/writing/style/)"
    updated:
        header: "Hello @{name}, Thank you for updating the PR!"
        footer: ""
    no_errors: "Great work! I discovered no PEP8 issues in this Pull Request. :1st_place_medal:"

scanner:
    diff_only: True  # Only show errors created by the new code

pycodestyle:
    max-line-length: 120  # Default PEP8 is 79, but allow 120 because a lot of people use wider screens nowadays...
    ignore:  # Errors and warnings to ignore
        - W191

only_mention_files_with_errors: True
descending_issues_order: False
