language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly
# command to install dependencies
install:
  - pip install .
  - pip install blinker
  - pip install flask_testing
  - pip install codecov
  - pip install nose-cov
  - pip install nose-exclude
# command to run tests
script:
  - nosetests --exclude-test=test_spotify.WindowsTests --nocapture --with-cov --cov-config .coveragerc

after_success:
- codecov
