sudo: true
language: python
python:
  - "3.4_with_system_site_packages"
  - "3.5_with_system_site_packages"
  - "3.6_with_system_site_packages"
  - nightly
  
# command to install dependencies
  
before_install:
- sudo apt-get install -qq python-dbus python3-dbus

install:
  - pip install python-dbusmock
  - pip install .
  - pip install codecov
  - pip install nose-cov
# command to run tests
addons:
  apt:
    packages:
    
    - dbus
    - dbus-x11

script: 
  - nosetests --nocapture --with-cov --cov-config .coveragerc

after_success:
  - codecov
