sudo: true
language: python
python:
  - "3.4_with_system_site_packages"
  - "3.5"
  - "3.6"
  - nightly

# command to install dependencies

before_install:
  - bash dbus_script.sh
  - sudo apt-get install -qq python-dbus python3-dbus python3-gi libdbus-glib-1-dev libdbus-1-3 libdbus-1-dev

install:
  - pip install python-dbusmock
  - pip install .
  - pip install codecov
  - pip install nose-cov
# command to run tests
addons:
  apt:
    packages:
    - dbus
    - dbus-x11

script:
  - nosetests --nocapture --with-cov --cov-config .coveragerc

after_success:
  - codecov
