language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly
# command to install dependencies
install:
  - sudo apt-get install python3-dbus
  - sudo apt-get install python-dbus
  - pip install python-dbusmock
  - pip install .
  - pip install codecov
  - pip install nose-cov
# command to run tests
script: 
  - nosetests --nocapture --with-cov --cov-config .coveragerc

after_success:
  - codecov
